### ISSUE TITLE
Need building instructions

### ISSUE THREAD

**Issue by abrahimladha** [matrix-org/matrix-android-console#13]
Could you please update the README with building instructions? they are not immediately obvious to me.

**Comment by ylecollen** [comment]
Abrahimladha, 
Could you explain here what you did not succeed to do?
If you already develop with android studio, it is quite simple;

**Comment by abrahimladha** [comment]
I know absolutely nothing about android studio, so If the building instructions were so obvious that they weren't necessary then I apologize. So they should be just open in android studio? and compile .apk? Theres nothing special externally?

**Comment by overflawio** [comment]
They have the gradle wrapper (so you need to type on the terminal `./gradlew build`).
What i discoveres is that you need first the `android-sdk` packet, the build-tools-21.0.0 (that is obsolete) and the google play services (i haven't builded it because i hate google play services and i don't want to download/build whit it)

but seriously guys... why the google play services? Plz...

**Comment by ylecollen** [comment]
1 - abrahimladha
here is the link which will save you 
https://developer.android.com/sdk/index.html
Issues are the place to explain how to install or use android studio.

2 - MascioSpam
The matrix sdk lib is included in the git-hub so you don't need to compile.
We use the google play services because most of the users will use a standard android device.
The questions are when developing a desktop software why windows and not linux.
