### ISSUE TITLE
Connection to my homeserver doesn't work

### ISSUE THREAD

**Issue by ghost** [matrix-org/matrix-android-console#3]
If I fill the login data with my homeserver url (https://matrix.myserver.com) I always receive:
"Unable to login: Network Error".

If I keep the default server (matrix.org) I can connect to my account there.
Is the url field a future feature?

I can connect to and use my server running synapse via web browser without any problems. 
I'm not using SRV records with synapse, just DNS adress.

**Comment by rrix** [comment]
I'm having this issue using either my SRV domain as the URL, or directly to my homeserver; I've imported the auto-generated cert on to my device, but it still doesn't work in Chrome, so I think that's the primary issue?

**Comment by erikjohnston** [comment]
What are the servers in questions, if I may ask?

Firstly, make sure you enter the url with the port, otherwise android will default to connecting to :443 which is probably not where your homeservers are running.

However, android really doesn't like our self signed certs, which is annoying. The workaround that people have discovered is to import your synapse's public cert into the android keystore, though you'll probably have to edit the cert to enable the "this is a CA cert". I'll try and find the exact instructions for you.

We know that this is really suboptimal, but we are trying to figure out the best way of fixing this.

**Comment by erikjohnston** [comment]
The JIRA issue tracking the self signed certs issue: https://matrix.org/jira/browse/SYAND-96 SkaveRat's comment includes the current workaround.

**Comment by rrix** [comment]
Thanks; I imported the crt without doing that, I'll try that today and report back.

**Comment by ghost** [comment]
Thanks! It works!
I have followed the JIRA tip and used the script by SkaveRat in: https://gist.github.com/SkaveRat/9fce0c63458c369a9095.
I have put the 3 tls files generated by the script into the synapse root folder.
Then, generate config for synapse again:

  python -m synapse.app.homeserver --server-name myserver.com --config-path homeserver.yaml   --generate-config

This command create a new signing.key file, according to your keys.

I'm using apache as proxy ssl from other host, so I have added the tls.crt and tls.key file to the virtual host on the apache machine.
Finally I have convert the ca.crt.pem generated by the script to binary format. The script says I could inmport the pem file, but my android 4.2 refuse to do it. So I did:

  sudo openssl x509 -in ca.crt.pem -inform PEM -out CA.crt -outform DER

and then import CA.crt into my android (menus way).

All the users in the server have to do that, as you say is very suboptimal.

IMHO, fingerprint confirmation is a good solution beetween the proposed ones at JIRA site.

**Comment by erikjohnston** [comment]
@pebelino Cool that it works :)  I'm currently working on getting basic fingerprint support working, hopefully it will only be another few days before there's a version available for people to test.

**Comment by ylecollen** [comment]
It seems fixed by now if i read the latest comments
